### ISSUE TITLE
natural-select : coherent model and search value

### ISSUE THREAD

**Issue by sambaptista** [Ecodev/natural#39] opened 2020-07-01 15:20 UTC
When using natural-select, we first type something to activate the autocomplete suggestions.

If we pick some suggestion, the input element is updated with the rendered value of the selected suggestion. But if we don't pick any value from suggestions, the input element still shows the searched value. 

It becomes confusing because the GUI shows some value, but the model is still the previous selected value (or null). 

When bluring the field we have to assume the search part is over and the searched text should be discarded. That means the selected model rendered value should take place in the input element.

care : there could be some caution to take when using the free text mode.

**Comment by PowerKiKi** [comment] 2023-03-09 11:28
Duplicate of #237

**Closed as not planned by PowerKiKi** 2023-03-09 11:28 UTC
Labels: enhancement, natural-select
