### ISSUE TITLE
Distinction between "clear current search" and "clear current selection"

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural#237] opened 2023-03-09 10:34 UTC
> This error led me to another issue due to the confusing behavior of the input & clear button  in the natural-select, even if it's not directly related to console error of this video.
> 
> The clear button does two things : clear the input field, and clear the selection !
> 
> In the usecase of this video, the clear button is used to cancel the search (for autocompletion). But doing so, we clear the value of the select and emit it to the (selectionChange) event listener.
> 
> This issue is true for every natural-select and must be fixed.
> 
> https://user-images.githubusercontent.com/5111137/223781325-a3865e84-fac9-4938-8368-a5ef1d60dda9.mov
> 
> Furthermore, even when the select is already empty : clearing the auto complete emits a "select empty value" event.
> 
> The RelationComponent.addRelation is called but receives an array with one null value `[null]`. 
> 
> The ambiguity comes from the point that the input field has two usages : display the selection and display the search for the autocompletion. What is the clear button supposed to do ?
> 
> Well I think when we're searching a value to open the autocomplete, the clear button should restore the last selection (null or any other previously selected value). In this case, there should be no output emited. It's just internal "navigation" into the natural-select.
> 
> When the natural-select already displays the selected value, the clear button should unselect it and emit and empty value.
> 
> 
> ---------------
> 
> Alternative minimal fix in RelationsComponent if we dont refactor the select : 
> 
> ```diff
> -        const observables = relations.map(relation =>
> +       const observables = relations.filter(r => !!r).map(relation =>
>             this.linkMutationService.link(this.main, relation, this.otherName),
>         );
> ```

_Originally posted by @sambaptista in https://github.com/Ecodev/natural/issues/236#issuecomment-1460530013_

**Comment by PowerKiKi** [comment] 2023-03-09 10:47
If we have two functionalities, we probably should have two different buttons, with different tooltips and different icons, to clarify when we do what.

But I am not so sure we need two buttons.

The fact that the "search text" is left behind even if there is a valid selection also happens if we delete the text entirely. Here I use CTRL+X to cut all text, and the input incorrectly keeps showing nothing even after the input loses focus:

https://user-images.githubusercontent.com/72603/224000338-3f9f9b53-8760-4864-a7fa-4ae04abfc2ac.mp4

So my suggestion is:

- the button clears the selection only, never the search text, and it probably should not be shown while searching
- the search text is always cleared when input loses focus, possibly restoring previous selection or showing nothing


PS: you came to the same conclusion as me, a long time ago, in #39

**Comment by sambaptista** [comment] 2023-04-06 16:24
Previous and actual reflexions are not in conflict. They are even complementary.

It's Fixed. 

In simple : Blur, Escape and "undo" button click revert the searched text from the input field into the actual committed model. 

By default there is a suffix button (X) that means : unset/clear/empty model. When searching, button turns into "undo" button (back arrow) that replace the searched value by the actual model.

Emptying the field with keyboard and hitting "ENTER" unsets the model. This can be discussed, but my thinking leads me to say ENTER should validate something (and not revert like Escape). And validating an empty value is a valid action for unsetting the model.

In the specific case of free text input, the undo button does not display because if we want to undo we **have to** blur first, and the blur action in this context validates the input.

I'll try to cover it with tests next week, but the issue is fixed.

**Closed as completed by sambaptista** 2023-04-06 16:24 UTC
Labels: bug, natural-select

**Comment by PowerKiKi** [comment] 2023-04-21 04:42
> Emptying the field with keyboard and hitting "ENTER" unsets the model

Totally fine by me.

I added a [few commits](https://github.com/Ecodev/natural/compare/5c3bd2d57c7aa5f2013162395a65027c0d022fe0...2266b747384e5387f1d992c6b0549c898bb82d19). It would be even better if [your useful comment](https://github.com/Ecodev/natural/issues/237#issuecomment-1499322843) here was actually the commit message, for ease of understanding code in the future. And also be careful to keep things as private as possible, since that makes refactoring much easier.
